New tests
JuliaPOMDP/POMDPTesting.jl pull request #7
Opened 2019-12-21 23:17 UTC by zsunberg

Given how many times we've needed to fix TMazes, I thought we could make some better tests. What do you guys think of these? They test more things like the initial state distribution and the support of all the distributions, etc.

2019-12-21 23:21 UTC, zsunberg commented
I need to create the Project.toml and write more tests to test the different branches but wanted to see if there are any big suggestions first

2019-12-22 02:54 UTC, rejuvyesh requested changes
This is great! Thanks for doing this!

2019-12-22 02:54 UTC, rejuvyesh commented on src/model.jl
> +                    @info "Transition probabilities sum to $psum, not 1." s a
Maybe more like `@warn`?

2019-12-22 02:54 UTC, rejuvyesh commented on src/model.jl
> +                    @info "Transition probabilities sum to $psum, not 1." s a
Same at others when `false`.

2020-01-26 01:42 UTC, zsunberg commented
@rejuvyesh @MaximeBouton any other suggestions? If not I will merge and tag this on Monday

2020-01-27 19:40 UTC, MaximeBouton approved these changes

2020-01-27 19:45 UTC, MaximeBouton commented
That looks much better thanks @zsunberg !

2020-01-28 11:44 UTC, rejuvyesh commented
Looks great and thanks for doing this! :shipit:

2020-01-28 11:44 UTC, rejuvyesh approved these changes

2020-01-28 11:45 UTC, merged